spring:
  application:
    name: spring-cloud-service-eureka
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    #使用服务端模式
    fetchRegistry: false
    #配置自己的eureka的地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/